#pragma once

#include <string_view>

namespace gqlxy::e2e {

static const std::string CaCert =
    R"(-----BEGIN CERTIFICATE-----
MIIBhTCCASugAwIBAgIUGY3oljLyBTx65tuSOau9z7bttP8wCgYIKoZIzj0EAwIw
GDEWMBQGA1UEAwwNZ3FseHktdGVzdC1jYTAeFw0yNjA0MDkxNjQzNTdaFw0zNjA0
MDYxNjQzNTdaMBgxFjAUBgNVBAMMDWdxbHh5LXRlc3QtY2EwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAASTeuOi1PFEJ8/AGHezDITCQDE0w5WCc+rVq8+SaPzvoiaW
IdR5H8wYLI46Sna7L32FtKELtezwQxbA1K82M8HMo1MwUTAdBgNVHQ4EFgQU7dOP
JCd+rr90NpvBNaBptwtIRlswHwYDVR0jBBgwFoAU7dOPJCd+rr90NpvBNaBptwtI
RlswDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiEAx724jCVGfIub
yOl0Am66zeJjSgPyIEuItGTQouCGeVQCIGfEIMyPwUJ7P1lvY8K/ZSLcs1Bb9R9z
XU80OjnHJ/Rq
-----END CERTIFICATE-----)";

static const std::string ServerCert =
    R"(-----BEGIN CERTIFICATE-----
MIIBjTCCATKgAwIBAgIUdzkUKiq+ixfZQJKw3fmCBHYFdkcwCgYIKoZIzj0EAwIw
GDEWMBQGA1UEAwwNZ3FseHktdGVzdC1jYTAeFw0yNjA0MDkxNjQzNTdaFw0zNjA0
MDYxNjQzNTdaMBQxEjAQBgNVBAMMCWxvY2FsaG9zdDBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABKb6VoprC4/7QQFdtb3MLbdWah8JIA7gwKKY3SxexXwOGZcXsrhN
JVeT6LuKhCC0x2GPOoriqzW7VouoclYiAfmjXjBcMBoGA1UdEQQTMBGCCWxvY2Fs
aG9zdIcEfwAAATAdBgNVHQ4EFgQUu0kRvXQrLoPaaB7YDOmpH8Str+owHwYDVR0j
BBgwFoAU7dOPJCd+rr90NpvBNaBptwtIRlswCgYIKoZIzj0EAwIDSQAwRgIhAMHJ
OHQdAMCNi+sUCy2VKH2SGQm5e7R2gWZcZXjx+9N1AiEA21JyhtXEAGs6PkI2kPDt
sWTf7BzGzfDob1bs3HkMTcM=
-----END CERTIFICATE-----)";

constexpr std::string_view ServerKey =
    R"(-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgntkjt7E/Cf3nQwee
zRWFN6zA1sD7CjBWzpEHxwBgSA6hRANCAASm+laKawuP+0EBXbW9zC23VmofCSAO
4MCimN0sXsV8DhmXF7K4TSVXk+i7ioQgtMdhjzqK4qs1u1aLqHJWIgH5
-----END PRIVATE KEY-----)";

}
